apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: skilanu-com-tls
spec:
  secretName: skilanu-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: skilanu.com
  dnsNames:
    - skilanu.com
    - www.skilanu.com
